import type { BuilderComponentDefinition } from "@/types/api";
import type {
  CatalogueCategory,
  CatalogueMeta,
  EnrichedCatalogueItem,
} from "./types";

const CATEGORY_MAP: Record<string, CatalogueCategory> = {
  hero: "hero",
  about: "about",
  gallery: "gallery",
  contact: "contact",
  faq: "faq",
  footer: "footer",
  cta: "cta",
  navigation: "navigation",
  services: "services",
  pricing: "pricing",
  testimonials: "testimonials",
};

const META_OVERRIDES: Record<string, Partial<CatalogueMeta>> = {
  "hero.basic": {
    tags: ["headline", "cta", "centered"],
    difficulty: "beginner",
    animation: "fade-up",
    supportedThemes: ["modern", "minimal", "cafe", "gym"],
    supportedIndustries: ["cafe", "clinic", "education", "real-estate"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #2563EB 0%, #60A5FA 100%)",
    kind: "section",
  },
  "hero.split": {
    tags: ["split", "image", "two-column"],
    difficulty: "intermediate",
    animation: "slide-in",
    supportedThemes: ["modern", "luxury", "restaurant"],
    supportedIndustries: ["restaurant", "salon", "furniture", "real-estate"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)",
    kind: "section",
  },
  "hero.video": {
    tags: ["video", "cinematic", "immersive"],
    difficulty: "advanced",
    animation: "scale-in",
    supportedThemes: ["creative", "dark", "gym"],
    supportedIndustries: ["gym", "hotel", "photography"],
    librarySource: "custom",
    accessibility: "partial",
    performance: "moderate",
    previewGradient: "linear-gradient(135deg, #0F172A 0%, #334155 100%)",
    kind: "section",
  },
  "gallery.grid": {
    tags: ["images", "grid", "portfolio"],
    difficulty: "beginner",
    animation: "stagger",
    supportedThemes: ["modern", "creative", "salon"],
    supportedIndustries: ["photography", "fashion", "furniture", "jewellery"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "moderate",
    previewGradient: "linear-gradient(135deg, #059669 0%, #34D399 100%)",
    kind: "section",
  },
  "gallery.carousel": {
    tags: ["slider", "images", "swipe"],
    difficulty: "intermediate",
    animation: "marquee",
    supportedThemes: ["restaurant", "hotel", "cafe"],
    supportedIndustries: ["restaurant", "hotel", "bakery"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "moderate",
    previewGradient: "linear-gradient(135deg, #D97706 0%, #FBBF24 100%)",
    kind: "section",
  },
  "contact.map": {
    tags: ["map", "location", "form"],
    difficulty: "intermediate",
    animation: "fade-in",
    supportedThemes: ["medical", "restaurant", "cafe"],
    supportedIndustries: ["cafe", "clinic", "restaurant", "real-estate"],
    librarySource: "shadcn",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #0891B2 0%, #22D3EE 100%)",
    kind: "section",
  },
  "faq.accordion": {
    tags: ["questions", "accordion", "support"],
    difficulty: "beginner",
    animation: "accordion",
    supportedThemes: ["modern", "medical", "minimal"],
    supportedIndustries: ["clinic", "gym", "education"],
    librarySource: "shadcn",
    accessibility: "aaa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #334155 0%, #64748B 100%)",
    kind: "section",
  },
  "footer.simple": {
    tags: ["copyright", "links", "minimal"],
    difficulty: "beginner",
    animation: "none",
    supportedThemes: ["modern", "minimal", "luxury"],
    supportedIndustries: ["cafe", "salon", "restaurant", "gym"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #171717 0%, #525252 100%)",
    kind: "section",
  },
  "cta.banner": {
    tags: ["conversion", "banner", "action"],
    difficulty: "beginner",
    animation: "fade-up",
    supportedThemes: ["modern", "gym", "creative"],
    supportedIndustries: ["gym", "fashion", "real-estate"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #E11D48 0%, #FB7185 100%)",
    kind: "section",
  },
  "about.story": {
    tags: ["story", "brand", "narrative"],
    difficulty: "beginner",
    animation: "reveal",
    supportedThemes: ["luxury", "cafe", "salon"],
    supportedIndustries: ["cafe", "salon", "jewellery", "hotel"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #C2410C 0%, #F97316 100%)",
    kind: "section",
  },
};

/** Platform-only effect wrappers (not in backend registry). */
export const EFFECT_CATALOGUE: EnrichedCatalogueItem[] = [
  {
    key: "effect.aurora",
    category: "backgrounds",
    displayName: "Aurora Background",
    description:
      "Soft animated gradient wash for hero sections and landing pages.",
    tags: ["gradient", "ambient", "hero"],
    difficulty: "intermediate",
    version: "1.0",
    animation: "aurora",
    supportedThemes: ["modern", "creative", "dark"],
    supportedIndustries: ["cafe", "photography", "fashion"],
    librarySource: "react-bits",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #2563EB 0%, #8B5CF6 100%)",
    kind: "effect",
  },
  {
    key: "effect.spotlight",
    category: "effects",
    displayName: "Spotlight",
    description:
      "Mouse-following radial highlight for premium interactive sections.",
    tags: ["mouse", "interactive", "glow"],
    difficulty: "intermediate",
    version: "1.0",
    animation: "spotlight",
    supportedThemes: ["dark", "luxury", "modern"],
    supportedIndustries: ["jewellery", "fashion", "hotel"],
    librarySource: "aceternity",
    accessibility: "partial",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #0F172A 0%, #2563EB 100%)",
    kind: "effect",
  },
  {
    key: "effect.particles",
    category: "backgrounds",
    displayName: "Particles",
    description: "Floating particle field for energy and depth behind content.",
    tags: ["particles", "ambient", "motion"],
    difficulty: "beginner",
    version: "1.0",
    animation: "float",
    supportedThemes: ["gym", "dark", "creative"],
    supportedIndustries: ["gym", "photography"],
    librarySource: "react-bits",
    accessibility: "aa",
    performance: "moderate",
    previewGradient: "linear-gradient(135deg, #1E3A8A 0%, #3B82F6 100%)",
    kind: "effect",
  },
  {
    key: "effect.infinite-cards",
    category: "animations",
    displayName: "Infinite Cards",
    description:
      "Horizontally scrolling card strip for services, tags, or highlights.",
    tags: ["carousel", "infinite", "cards"],
    difficulty: "intermediate",
    version: "1.0",
    animation: "marquee",
    supportedThemes: ["modern", "minimal"],
    supportedIndustries: ["salon", "restaurant", "education"],
    librarySource: "aceternity",
    accessibility: "aa",
    performance: "moderate",
    previewGradient: "linear-gradient(135deg, #6366F1 0%, #A78BFA 100%)",
    kind: "effect",
  },
  {
    key: "effect.animated-grid",
    category: "backgrounds",
    displayName: "Animated Grid",
    description: "Subtle pulsing grid pattern for tech and studio aesthetics.",
    tags: ["grid", "pattern", "subtle"],
    difficulty: "beginner",
    version: "1.0",
    animation: "pulse",
    supportedThemes: ["modern", "minimal", "dark"],
    supportedIndustries: ["real-estate", "education"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 100%)",
    kind: "effect",
  },
  {
    key: "effect.marquee",
    category: "animations",
    displayName: "Marquee",
    description:
      "Continuous text ticker for announcements, brands, or social proof.",
    tags: ["ticker", "text", "scroll"],
    difficulty: "beginner",
    version: "1.0",
    animation: "marquee",
    supportedThemes: ["modern", "gym", "creative"],
    supportedIndustries: ["gym", "fashion", "cafe"],
    librarySource: "react-bits",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #F43F5E 0%, #FB7185 100%)",
    kind: "effect",
  },
  {
    key: "effect.text-reveal",
    category: "animations",
    displayName: "Text Reveal",
    description: "Blur-to-sharp headline entrance on scroll into view.",
    tags: ["typography", "reveal", "scroll"],
    difficulty: "beginner",
    version: "1.0",
    animation: "reveal",
    supportedThemes: ["luxury", "minimal", "salon"],
    supportedIndustries: ["salon", "jewellery", "hotel"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #1C1917 0%, #A68B5B 100%)",
    kind: "effect",
  },
  {
    key: "effect.scroll-reveal",
    category: "animations",
    displayName: "Scroll Reveal",
    description: "Wrap any block with a smooth fade-up entrance on scroll.",
    tags: ["scroll", "fade", "wrapper"],
    difficulty: "beginner",
    version: "1.0",
    animation: "fade-up",
    supportedThemes: ["modern", "minimal", "medical"],
    supportedIndustries: ["clinic", "furniture", "bakery"],
    librarySource: "custom",
    accessibility: "aa",
    performance: "light",
    previewGradient: "linear-gradient(135deg, #059669 0%, #34D399 100%)",
    kind: "effect",
  },
];

export function enrichCatalogueItem(
  component: BuilderComponentDefinition,
): EnrichedCatalogueItem {
  const category =
    CATEGORY_MAP[component.category] ?? ("hero" as CatalogueCategory);
  const override = META_OVERRIDES[component.key] ?? {};

  return {
    key: component.key,
    category,
    displayName: component.displayName,
    description: component.description ?? "",
    variants: component.variants,
    settingsSchema: component.settingsSchema,
    tags: override.tags ?? [component.category],
    difficulty: override.difficulty ?? "beginner",
    version: "1.0",
    animation: override.animation ?? "fade-up",
    supportedThemes: override.supportedThemes ?? ["modern", "minimal"],
    supportedIndustries: override.supportedIndustries ?? ["cafe", "restaurant"],
    librarySource: override.librarySource ?? "custom",
    accessibility: override.accessibility ?? "aa",
    performance: override.performance ?? "light",
    previewGradient:
      override.previewGradient ??
      "linear-gradient(135deg, #2563EB 0%, #60A5FA 100%)",
    kind: override.kind ?? "section",
  };
}

export function enrichCatalogue(
  components: BuilderComponentDefinition[],
): EnrichedCatalogueItem[] {
  return components.map(enrichCatalogueItem);
}

/** Backend sections + platform effect wrappers. */
export function getFullCatalogue(
  components: BuilderComponentDefinition[],
): EnrichedCatalogueItem[] {
  return [...enrichCatalogue(components), ...EFFECT_CATALOGUE];
}

export const CATALOGUE_CATEGORIES: CatalogueCategory[] = [
  "navigation",
  "hero",
  "about",
  "gallery",
  "services",
  "pricing",
  "testimonials",
  "faq",
  "contact",
  "cta",
  "footer",
  "backgrounds",
  "animations",
  "effects",
];

export const LIBRARY_SOURCE_LABELS: Record<string, string> = {
  custom: "Custom",
  "react-bits": "React Bits",
  shadcn: "shadcn",
  aceternity: "Aceternity",
};
