import type { IndustryPreset } from "./types";

export const INDUSTRY_PRESETS: IndustryPreset[] = [
  {
    id: "cafe",
    name: "Café",
    icon: "☕",
    description: "Warm, inviting websites for coffee shops and bakeries.",
    recommendedThemeId: "cafe",
    recommendedPaletteId: "warm",
    recommendedPages: ["Home", "Menu", "About", "Contact"],
    recommendedSections: [
      "hero.basic",
      "gallery.grid",
      "about.story",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#D97706",
  },
  {
    id: "restaurant",
    name: "Restaurant",
    icon: "🍽️",
    description: "Appetizing layouts for dining and hospitality.",
    recommendedThemeId: "restaurant",
    recommendedPaletteId: "rose",
    recommendedPages: ["Home", "Menu", "Reservations", "Contact"],
    recommendedSections: [
      "hero.split",
      "gallery.carousel",
      "cta.banner",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#E11D48",
  },
  {
    id: "gym",
    name: "Gym",
    icon: "💪",
    description: "High-energy sites for fitness and wellness centers.",
    recommendedThemeId: "gym",
    recommendedPaletteId: "blue",
    recommendedPages: ["Home", "Classes", "Pricing", "Contact"],
    recommendedSections: [
      "hero.video",
      "cta.banner",
      "faq.accordion",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#2563EB",
  },
  {
    id: "salon",
    name: "Salon",
    icon: "✂️",
    description: "Elegant presence for beauty and grooming brands.",
    recommendedThemeId: "salon",
    recommendedPaletteId: "rose",
    recommendedPages: ["Home", "Services", "Gallery", "Book"],
    recommendedSections: [
      "hero.split",
      "gallery.grid",
      "about.story",
      "cta.banner",
      "footer.simple",
    ],
    colorAccent: "#EC4899",
  },
  {
    id: "hotel",
    name: "Hotel",
    icon: "🏨",
    description: "Luxury hospitality with immersive imagery.",
    recommendedThemeId: "luxury",
    recommendedPaletteId: "neutral",
    recommendedPages: ["Home", "Rooms", "Amenities", "Book"],
    recommendedSections: [
      "hero.video",
      "gallery.carousel",
      "about.story",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#A68B5B",
  },
  {
    id: "jewellery",
    name: "Jewellery",
    icon: "💎",
    description: "Premium showcase for fine jewellery and watches.",
    recommendedThemeId: "luxury",
    recommendedPaletteId: "amber",
    recommendedPages: ["Home", "Collections", "About", "Contact"],
    recommendedSections: [
      "hero.basic",
      "gallery.grid",
      "about.story",
      "cta.banner",
      "footer.simple",
    ],
    colorAccent: "#D97706",
  },
  {
    id: "furniture",
    name: "Furniture",
    icon: "🪑",
    description: "Clean product-focused layouts for home and décor.",
    recommendedThemeId: "minimal",
    recommendedPaletteId: "neutral",
    recommendedPages: ["Home", "Catalogue", "About", "Contact"],
    recommendedSections: [
      "hero.split",
      "gallery.grid",
      "about.story",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#525252",
  },
  {
    id: "clinic",
    name: "Clinic",
    icon: "🏥",
    description: "Trust-building sites for healthcare providers.",
    recommendedThemeId: "medical",
    recommendedPaletteId: "cool",
    recommendedPages: ["Home", "Services", "Team", "Contact"],
    recommendedSections: [
      "hero.basic",
      "about.story",
      "faq.accordion",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#0891B2",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    icon: "🏠",
    description: "Property showcases with search and listings.",
    recommendedThemeId: "modern",
    recommendedPaletteId: "slate",
    recommendedPages: ["Home", "Listings", "About", "Contact"],
    recommendedSections: [
      "hero.split",
      "gallery.grid",
      "cta.banner",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#334155",
  },
  {
    id: "education",
    name: "Education",
    icon: "📚",
    description: "Clear, accessible sites for schools and coaching.",
    recommendedThemeId: "minimal",
    recommendedPaletteId: "emerald",
    recommendedPages: ["Home", "Courses", "About", "Contact"],
    recommendedSections: [
      "hero.basic",
      "about.story",
      "faq.accordion",
      "cta.banner",
      "footer.simple",
    ],
    colorAccent: "#059669",
  },
  {
    id: "bakery",
    name: "Bakery",
    icon: "🥐",
    description: "Warm product galleries for patisseries and bake shops.",
    recommendedThemeId: "cafe",
    recommendedPaletteId: "warm",
    recommendedPages: ["Home", "Menu", "Custom Orders", "Contact"],
    recommendedSections: [
      "hero.basic",
      "gallery.grid",
      "about.story",
      "contact.map",
      "footer.simple",
    ],
    colorAccent: "#D97706",
  },
  {
    id: "photography",
    name: "Photography",
    icon: "📷",
    description: "Portfolio-first layouts for photographers and studios.",
    recommendedThemeId: "minimal",
    recommendedPaletteId: "neutral",
    recommendedPages: ["Home", "Portfolio", "Services", "Book"],
    recommendedSections: [
      "hero.basic",
      "gallery.grid",
      "about.story",
      "cta.banner",
      "footer.simple",
    ],
    colorAccent: "#525252",
  },
  {
    id: "fashion",
    name: "Fashion Boutique",
    icon: "👗",
    description: "Lookbook layouts for apparel and boutique brands.",
    recommendedThemeId: "luxury",
    recommendedPaletteId: "rose",
    recommendedPages: ["Home", "Collections", "About", "Visit"],
    recommendedSections: [
      "hero.split",
      "gallery.grid",
      "about.story",
      "cta.banner",
      "footer.simple",
    ],
    colorAccent: "#E11D48",
  },
];

export function getIndustryPreset(id: string): IndustryPreset | undefined {
  return INDUSTRY_PRESETS.find((p) => p.id === id);
}
