import type { PlatformTheme } from "./types";

export const PLATFORM_THEMES: PlatformTheme[] = [
  {
    id: "modern",
    name: "Modern",
    description:
      "Clean lines, bold typography, and confident spacing for tech-forward brands.",
    industryTags: ["general", "startup", "agency"],
    previewGradient: "linear-gradient(135deg, #2563EB 0%, #60A5FA 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.75rem",
    animationStyle: "subtle",
    defaultPaletteId: "blue",
    supportedPalettes: ["blue", "slate", "neutral", "cool"],
  },
  {
    id: "luxury",
    name: "Luxury",
    description:
      "Refined elegance with generous whitespace and premium gold accents.",
    industryTags: ["jewellery", "hotel", "salon"],
    previewGradient: "linear-gradient(135deg, #1C1917 0%, #A68B5B 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.25rem",
    animationStyle: "minimal",
    defaultPaletteId: "neutral",
    supportedPalettes: ["neutral", "amber", "rose", "slate"],
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Stripped-back design that lets your content breathe.",
    industryTags: ["portfolio", "creative", "education"],
    previewGradient: "linear-gradient(135deg, #FAFAFA 0%, #E5E5E5 100%)",
    fontDisplay: "var(--font-inter)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.5rem",
    animationStyle: "minimal",
    defaultPaletteId: "neutral",
    supportedPalettes: ["neutral", "slate", "cool"],
  },
  {
    id: "cafe",
    name: "Café",
    description:
      "Warm, inviting aesthetics perfect for coffee shops and bakeries.",
    industryTags: ["cafe", "bakery", "restaurant"],
    previewGradient: "linear-gradient(135deg, #92400E 0%, #FBBF24 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "1rem",
    animationStyle: "expressive",
    defaultPaletteId: "warm",
    supportedPalettes: ["warm", "amber", "neutral"],
  },
  {
    id: "restaurant",
    name: "Restaurant",
    description:
      "Rich imagery and appetite-stoking layouts for dining experiences.",
    industryTags: ["restaurant", "hotel"],
    previewGradient: "linear-gradient(135deg, #7F1D1D 0%, #DC2626 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.5rem",
    animationStyle: "subtle",
    defaultPaletteId: "rose",
    supportedPalettes: ["rose", "warm", "amber"],
  },
  {
    id: "gym",
    name: "Gym",
    description: "High-energy design with bold contrasts and dynamic motion.",
    industryTags: ["gym", "fitness", "sports"],
    previewGradient: "linear-gradient(135deg, #0F172A 0%, #2563EB 100%)",
    fontDisplay: "var(--font-inter)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.375rem",
    animationStyle: "expressive",
    defaultPaletteId: "blue",
    supportedPalettes: ["blue", "slate", "emerald"],
  },
  {
    id: "medical",
    name: "Medical",
    description: "Trust-building clarity for clinics and healthcare providers.",
    industryTags: ["clinic", "medical", "dental"],
    previewGradient: "linear-gradient(135deg, #ECFEFF 0%, #0891B2 100%)",
    fontDisplay: "var(--font-inter)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.75rem",
    animationStyle: "minimal",
    defaultPaletteId: "cool",
    supportedPalettes: ["cool", "emerald", "blue"],
  },
  {
    id: "salon",
    name: "Salon",
    description: "Soft, sophisticated styling for beauty and wellness brands.",
    industryTags: ["salon", "spa", "beauty"],
    previewGradient: "linear-gradient(135deg, #FDF2F8 0%, #EC4899 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "1.25rem",
    animationStyle: "subtle",
    defaultPaletteId: "rose",
    supportedPalettes: ["rose", "purple", "neutral"],
  },
  {
    id: "creative",
    name: "Creative",
    description: "Expressive layouts for agencies, studios, and makers.",
    industryTags: ["creative", "agency", "portfolio"],
    previewGradient: "linear-gradient(135deg, #7C3AED 0%, #F43F5E 100%)",
    fontDisplay: "var(--font-instrument-serif)",
    fontBody: "var(--font-inter)",
    borderRadius: "1.5rem",
    animationStyle: "expressive",
    defaultPaletteId: "purple",
    supportedPalettes: ["purple", "rose", "amber"],
  },
  {
    id: "dark",
    name: "Dark",
    description: "Immersive dark-mode experience with luminous accents.",
    industryTags: ["tech", "nightlife", "creative"],
    previewGradient: "linear-gradient(135deg, #0F1115 0%, #2563EB 100%)",
    fontDisplay: "var(--font-inter)",
    fontBody: "var(--font-inter)",
    borderRadius: "0.75rem",
    animationStyle: "subtle",
    defaultPaletteId: "blue",
    supportedPalettes: ["blue", "purple", "emerald", "cool"],
  },
];

export function getTheme(id: string): PlatformTheme {
  return PLATFORM_THEMES.find((t) => t.id === id) ?? PLATFORM_THEMES[0];
}
